spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://223.3.72.234:3306/disputeweb?characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
          hibernate:
            hbm2ddl:
              auto: update
  redis:
    host: 223.3.79.0
    port: 6379

server:
  port: 443
  ssl:
    key-store-type: JKS
    key-store: classpath:1541430928812.jks
    key-store-password: 1541430928812
    # 证书别名
    key-alias: alias



mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

qiniu:
  accessKey: jQgwEQyvj26BfIqkzKJRAKUNKBHSY1rhToRAmL0S
  secretKey: FmohAKLBvw22u9MKAwxKwV1a2mgI-brc3WWhlFmf
  bucket: disputeweb
  path: pe93soaos.bkt.clouddn.com


security:
  require-ssl: true

#自定义路径
py:
  path: ./src/main/resources/pyfiles/

webrtcKeys:
  path: ./src/main/resources/webrtcKeys/
