spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.0.16:3306/disputeweb?characterEncoding=utf-8&useSSL=false&autoReconnect=true
#    url: jdbc:mysql://139.199.166.125:3306/disputeweb?characterEncoding=utf-8&useSSL=false&autoReconnect=true

    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
          hibernate:
            hbm2ddl:
              auto: update
  redis:
    host: 172.16.0.16

#    host: 139.199.166.125
    port: 6379

server:
#  port: 8080
  port: 443
  ssl:
    key-store-type: JKS
    key-store: classpath:1541430928812.jks
    key-store-password: 1541430928812
    # 证书别名
    key-alias: alias



mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

qiniu:
  accessKey: ehkBu3JZo2DwT9vJXEpWOr-ZqPhMX8g-c9sXq5MX
  secretKey: ZR9jqxtOZuYYhAoGELNpoWpWpCB8NUqA7iznAEz0
  bucket: disputeweb
  path: phcgv7nm3.bkt.clouddn.com


#security:
#  require-ssl: true

#自定义路径


