spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://223.3.78.235:3306/disputeWeb?characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
          hibernate:
            hbm2ddl:
              auto: update


server:
  port: 8088

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


